### ISSUE TITLE
DISPATCHES repository reorganization

### ISSUE THREAD

**Issue by jghouse88** [gmlc-dispatches/dispatches#104]
Folders are organized according to case studies and there are models that are common to two different case studies. For example, PEM unit model is currently under `renewables_case` but it is also used in `nuclear_case`. Similarly, hydrogen turbine currently is within `nuclear_case` but is used in the `renewables_case` as well. Suggested reorg post discussion during meeting on 04/25/2022 is as follows:

`dispatches`

> `unit_models`
> `flowsheets`
> `utilities`
> `examples`
> > `nuclear_case`
> > `fossil_case`
> > `renewables_case`

**Comment by ksbeattie** [comment]
We should schedule this reorg carefully, as it will create conflicts with pretty much all open PRs.  The best time might be right after the April/May release, when there will hopefully be a minimum of open PRs and to allow plenty of time to resolve conflicts.

**Comment by adowling2** [comment]
+1 to the suggestion from @ksbeattie (which I think was also raised in the call today).

**Comment by adowling2** [comment]
@jghouse88 Does it make sense to replace `utilities` with `workflow`. IMO, `workflow` is a more appropriate name for the code related to surrogates, etc. Perhaps it is more encompassing than `utilities`.
