### ISSUE TITLE
Resolve Jupyter notebooks errors

### ISSUE THREAD

**Issue by lbianchi-lbl** [gmlc-dispatches/dispatches#127]
As part of the notebook infrastructure being added in #126, running the automated tests on the existing Jupyter notebooks resulted in several errors. These will need to be addressed before we can use the notebook tests as part of the CI; more in general, it's likely that these errors are due to running the notebook in an isolated environment and therefore would also affect external users.

**EDIT** I've created a [Wiki page](https://github.com/gmlc-dispatches/dispatches/wiki/How-to:-prepare-notebooks-so-that-all-checks-pass) with information on how to prepare notebooks so that all checks pass.

### RE case

- [ ] `DoubleLoopOptimization.ipynb`
  - [x] Cell 10 times out (> 600 s) on Windows
  - [ ] Cell 10 raises exception on Linux because of capitalization issues in the GMLC-RTS dataset (see gmlc-dispatches/sample-data#1)
  - [x] Requires unreleased version of `idaes-pse` that's incompatible with other (pre-existing) DL notebooks

**Comment by lbianchi-lbl** [comment]
@dguittet, re: reducing the runtime of RE `DoubleLoopOptimization.ipynb`, summarizing what I understand from your suggestions:

- Setting `num_days` in the Prescient options to e.g. 1 instead of 7 should result in a lower runtime
- We need a way to set this value conditionally to use the lower values for testing, and leave the default 7 in the notebooks, since the user-facing text in the notebooks refer to this value, and more generally results in a more interesting simulation

Following our discussion on what'd be the best way to implement this logic, what about the following:

- Since this problem is not specific to this particular notebook, we can set a package-level variable (e.g. `TESTING_MODE`) to keep track whether the code is being run in testing mode:

  ```py
  # in dispatches.py
  import os

  TESTING_MODE = bool(os.environ.get("DISPATCHES_TESTING_MODE", None))
  ```

- Somewhere at the beginning of the notebook, import `TESTING_MODE` to make it accessible throughout the notebook
- In Cell 2, set the value of `sim_days` conditionally depending on the value of `TESTING_MODE`:

  ```py
  
  sim_days = 7 if not TESTING_MODE else 1
  ...
  ```

The reason why I think it'd make sense to have this more generic implementation is that I imagine we could use this (or a similar) pattern for any other notebook that might require a shorter runtime for CI. Let me know what you think.

**Comment by dguittet** [comment]
Only problem remaining here is the RTS_GMLC capitalization problem on Linux

**Comment by dguittet** [comment]
Closing this issue and moving the remaining issue to the parent issue
