### ISSUE TITLE
Store large data files for surrogate models.

### ISSUE THREAD

**Issue by Xinhe-Chen** [gmlc-dispatches/dispatches#144]
To develop surrogate models we need to use large csv files (Dispatch_shuffled_data_0.csv, ~400M). However, we can not put them in the dispatches main repo. We need to discuss where to put those files. 
@ksbeattie @lbianchi-lbl @adowling2

**Comment by adowling2** [comment]
Our current working plan is to use Box. Worst case, my group has a paid GitHub subscription that includes storage. Although I think GitHub allows for large repos if they are public. Could we have a dispatches/large-data repo?

**Comment by adowling2** [comment]
Summary of conversation from today:
- Use Box, for now, to share files across the team
- Pandas can read in zip files
- Explore creating `large-data` repo, use GitHub large file support
- These files will be used to reproduce results, likely not needed for integration testing.
