### ISSUE TITLE
Unify underbind and wind waste penatlies in tracker of double loop

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#147]
@dguittet implemented a wind waste penalty inside the RE case study model that is used in the double loop:
https://github.com/gmlc-dispatches/dispatches/blob/31cd536418ee7b8dd253f062c9976ab1aa9e4cab/dispatches/case_studies/renewables_case/wind_battery_double_loop.py#L175

@Xinhe-Chen will add code from @xiangao1 that introduces underbid penalty, please add coordinates to the code here, need to add PR into IDAES that adds underbid

**Comment by adowling2** [comment]
@dguittet tested double loop (RE case study) with and without wind waste penalty, battery SOC is higher with the penalty

**Comment by Xinhe-Chen** [comment]
I uploaded a few missing file from @xiangao1 here:
https://github.com/Xinhe-Chen/dispatches/tree/RE_case_study/dispatches/models/renewables_case

* run_double_loop_latest.py: This file includes the real-time underbidding penalty options and simulation batch option for the double-loop. This file is needed to reproduce the results in @xiangao1 thesis. 

* result_analysis_utils.py: This file includes the functions to generate contour plots used in sensitivity_analysis.ipynb. 

Here is the specified commits. 
https://github.com/Xinhe-Chen/dispatches/commit/41fd78328ec9fe1def8a1397b6e079dd086f8de6

**Comment by ksbeattie** [comment]
dup of #148
