### ISSUE TITLE
Fix discharge flowsheet in fossil case study

### ISSUE THREAD

**Issue by radhakrishnatg** [gmlc-dispatches/dispatches#153]
@nareshsusarla @esrawli 
After making the changes in #151 , the discharge flowsheet is not working. For now, we plan to merge the PR with the test failure. Please take a look at the flowsheet and make necessary changes.

- [x] Test for the discharge flowsheet and update the design Jupyter notebook
- [x] The price-taker notebook is also having convergence issues. For now, `nbval-skip` tag was added to skip a few cells. We need to remove the tags after addressing the issue.
- [x] I updated the Jupyter notebook for the double loop simulation. Now, we use `Backcaster` class as the forecaster. The class requires the bus name, the day-ahead and real-time LMPs. see cell 2. Please update the bus name and LMPs based on the generator you chose and re-run the notebook. I observed that some of the runs in the double loop simulation are not converging. Apparently, this was also the case with the existing version of the notebook. Please take a look at the convergence issues too.

**Comment by nareshsusarla** [comment]
The failing tests are due to the tests for discharge flowsheet. The Discharge flowsheet is working as expected locally without the need for any changes. Also, the tests are passing locally. Need further analysis on why they are failing in github.

**Comment by nareshsusarla** [comment]
All of these are now addressed in the PR, which is up for review. Once the PR is merged this issue can be closed.
