### ISSUE TITLE
Jupyter Notebook Failures

### ISSUE THREAD

**Issue by MarcusHolly** [gmlc-dispatches/dispatches#200]
I ran into a few errors when running the Jupyter notebooks for some of the case studies before and after the latest MultiPeriodModel PR: https://github.com/IDAES/idaes-pse/pull/1180. Some of these might already be known (and acceptable), but there are also some that should probably be addressed. It's also possible that some of these failures are a result of my environment missing a few things, in which case the default configuration should probably be updated.

- [x] dispatches/case_studies/nuclear_case/nuclear_flowsheet_double_loop.ipynb
When Gurobipy is not installed in my environment:
![image](https://github.com/gmlc-dispatches/dispatches/assets/96305519/9f7221c7-78d1-4efe-ab90-1e687db3c815)

When Gurobipy is installed in my environment:
![image](https://github.com/gmlc-dispatches/dispatches/assets/96305519/ed8197a1-cb2f-4978-ab02-8420f6616afe)

- [x] dispatches/case_studies/nuclear_case/multiperiod_design_pricetaker_wTEALandSynhist.ipynb
After running `pip install TEAL`, I still get this error:
![image](https://github.com/gmlc-dispatches/dispatches/assets/96305519/f1b02afb-1fed-4ae5-bf59-f3df9b4f4fdd)

- [ ] dispatches/case_studies/renewables_case/DoubleLoopOptimization.ipynb
![image](https://github.com/gmlc-dispatches/dispatches/assets/96305519/dc344c7b-e65b-4fc4-a111-fa52af34dabc)

**Comment by lbianchi-lbl** [comment]
@lbianchi-lbl and @radhakrishnatg discussed these 3 issues during the dev call. We'll add more information on how we think they could be addressed later.

**Comment by radhakrishnatg** [comment]
@MarcusHolly Could you please run the `renewables_case/DoubleLoopOptimization.ipynb` once again? I just ran the notebook on my laptop and I did not get that error message. @lbianchi-lbl Is this notebook tested in the CI?

**Comment by radhakrishnatg** [comment]
Update on the remaining issues:
(1) I opened PR #202 to fix the issue related to gurobi. I have added a check at the beginning of the notebook (similar to the one in the RE case study) that uses `cbc` as the linear solver if gurobi is not available.
(2) The TEAL issue is related to two things: python version (currently it is compatible only with python 3.8), and RAVEN and TEAL are not installed by default. We need to run `pip install -r requirements-raven.txt` to install those packages.

**Comment by MarcusHolly** [comment]
@radhakrishnatg After uninstalling Gurobi, I'm still running into the same error for `renewables_case/DoubleLoopOptimization.ipynb`

After running `pip install -r requirements-teal.txt`, I'm no longer running into any issues for nuclear_case/multiperiod_design_pricetaker_wTEALandSynhist.ipynb

**Comment by radhakrishnatg** [comment]
Thank you @MarcusHolly I did not run the notebook properly before. I ran it again, and I did get the `ValueError` message. I guess this cell was skipped in the notebook tests. This needs to be fixed. @dguittet could you please take a look at the notebook and see what is causing this error message?

**Comment by lbianchi-lbl** [comment]
> Thank you @MarcusHolly I did not run the notebook properly before. I ran it again, and I did get the `ValueError` message. I guess this cell was skipped in the notebook tests. This needs to be fixed. @dguittet could you please take a look at the notebook and see what is causing this error message?

@radhakrishnatg I believe the notebook itself is tested in CI, but it might be the case that this cell is skipped and/or depends on a previous cell that's being skipped (e.g. if the code in this cell is supposed to be executed post-solve).
