### ISSUE TITLE
Prescient Dependency Requirement when running Dispatches

### ISSUE THREAD

**Issue by klfrick2** [gmlc-dispatches/dispatches#26]
When running off a dispatches PR. (PR10 to be exact). When the model hydrogen_turbine_combined_TGSet.py is run a failure occurs claiming the module "prescient" needs to be present. 

```
Traceback (most recent call last):
  File "C:/Users/FRICKL/projects/GMI_work/dispatches/dispatches/models/nuclear_case/Hydrogen_Turbine/hydrogen_turbine_combined_TGSet.py", line 24, in <module>
    from dispatches.dispatches.models.nuclear_case.Hydrogen_Turbine.hturbine_ideal_vap import configuration
  File "C:\Users\FRICKL\projects\GMI_work\dispatches\dispatches\__init__.py", line 5, in <module>
    from .workflow import ManagedWorkflow
  File "C:\Users\FRICKL\projects\GMI_work\dispatches\dispatches\workflow\__init__.py", line 2, in <module>
    from .workflow import ManagedWorkflow
  File "C:\Users\FRICKL\projects\GMI_work\dispatches\dispatches\workflow\workflow.py", line 21, in <module>
    from . import rts_gmlc
  File "C:\Users\FRICKL\projects\GMI_work\dispatches\dispatches\workflow\rts_gmlc.py", line 19, in <module>
    import prescient.downloaders.rts_gmlc as rts_downloader
ModuleNotFoundError: No module named 'prescient'
```

All that is needed for this model is hydrogen properties and idaes generic models.

**Comment by adowling2** [comment]
@dangunter Is this related to the DMF?

```
File "C:\Users\FRICKL\projects\GMI_work\dispatches\dispatches\__init__.py", line 5, in <module>
    from .workflow import ManagedWorkflow
```

**Comment by jghouse88** [comment]
I thought the same but I see that https://github.com/gmlc-dispatches/dispatches/blob/main/requirements.txt has `gridx-prescient` requirement. `requirements-dev.txt` does not have this, however, `setup.py` only looks at `requirements.txt`. 

@klfrick2 Can you run `python setup.py` and see if it fixes this issue?

**Comment by bknueven** [comment]
I was *not* able to replicate this issue with a fresh conda environment on Linux. I'm guessing this would be be fixed my merging in current main and rerunning setup.py as @jghouse88 suggests.

**Comment by ksbeattie** [comment]
Same here.  I tried from both of @klfrick2's dispatches-1 (pre public/broken fork) and dispatches (post public/correct fork) and other than having to replace `dispatches.dispatches` with just `dispatches` during imports, it worked.

@klfrick2 can you close this issue if you agree this isn't a problem anymore?

**Comment by jghouse88** [comment]
I get this when I run pytest from the top directory, tests pass but I am not sure what the warnings are about. 

`=================================================================================================================================== warnings summary ====================================================================================================================================
..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\common\config.py:236
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\common\config.py:236: DeprecationWarning: invalid escape sequence \h
    """=================================

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\misc.py:153
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\misc.py:153: DeprecationWarning: invalid escape sequence \s
    whitespace_re = re.compile('\s+')

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\misc.py:157
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\misc.py:157: DeprecationWarning: invalid escape sequence \s
    """

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\import_file.py:11
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\import_file.py:11: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\log_config.py:15
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\log_config.py:15: DeprecationWarning: invalid escape sequence \s
    _indention = re.compile('\s*')

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\log_config.py:16
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyutilib-6.0.0-py3.8.egg\pyutilib\misc\log_config.py:16: DeprecationWarning: invalid escape sequence \[
    _status_re = re.compile('^\[\s*[A-Za-z0-9\.]+\s*\]')

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\common\download.py:94
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\common\download.py:94: DeprecationWarning: invalid escape sequence \.
    if re.match('^[0-9\.]+', word):

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\opt\base\solvers.py:57
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\opt\base\solvers.py:57: DeprecationWarning: invalid escape sequence \.
    m = re.search('[0-9]+(\.[0-9]+){1,3}',x)

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checker.py:80
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checker.py:80: DeprecationWarning: invalid escape sequence \.
    match = re.search("<class '([a-zA-Z0-9_\.]+)'>", str(self.__class__))

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checker.py:84
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checker.py:84: DeprecationWarning: invalid escape sequence \.
    match = re.search("<class '([a-zA-Z0-9_\.]+)'>", str(self.__class__))

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checkers\py3k\printing.py:26
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\checker\plugins\checkers\py3k\printing.py:26: DeprecationWarning: invalid escape sequence \(
    if re.search("print[^\(]", line) is not None:

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\neos\kestrel.py:278
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\neos\kestrel.py:278: DeprecationWarning: invalid escape sequence \s
    m = re.search('solver\s*=*\s*(\S+)',self.options,re.IGNORECASE)

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\CPLEX.py:900
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\CPLEX.py:900: DeprecationWarning: invalid escape sequence \d
    elif re.match('clone\d+\.log', filename) != None:

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\CPLEX.py:898
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\CPLEX.py:898: DeprecationWarning: invalid escape sequence \.
    if  re.match('cplex\.log', filename) != None:

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\GUROBI.py:539
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\solvers\plugins\solvers\GUROBI.py:539: DeprecationWarning: invalid escape sequence \.
    if  re.match('gurobi\.log', filename) != None:

..\..\..\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\contrib\pynumero\interfaces\nlp.py:10
  C:\Users\jghouse\Anaconda3\envs\dispatches\lib\site-packages\pyomo-5.7.3-py3.8-win-amd64.egg\pyomo\contrib\pynumero\interfaces\nlp.py:10: DeprecationWarning: invalid escape sequence \i
    """The pyomo.contrib.pynumero.interfaces.nlp module includes abstract

-- Docs: https://docs.pytest.org/en/stable/warnings.html`

**Comment by jghouse88** [comment]
Thanks @jsiirola!
