### ISSUE TITLE
Update idaes-pse requirement in requirements.txt

### ISSUE THREAD

**Issue by jghouse88** [gmlc-dispatches/dispatches#47]
Currently, there is a mismatch in the idaes version that is installed in `requirements.txt` and what is used when running tests on GitHub. The `requirements.txt` file installs a release version while the tests are run against the idaes-pse main. We need to update the `requirements.txt` to install the idaes-pse main.

**Comment by lbianchi-lbl** [comment]
This makes sense. I'm looking into this, including the GitHub Actions setup, and it should be straightforward to set this up.

**Comment by jghouse88** [comment]
Thanks @lbianchi-lbl!
