### ISSUE TITLE
Generalize self-schedule bidder

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#83]
Goal: generalize the customized self-schedule bidding method implemented for the RE case study.

Lead: @isatkaus

Support: @xiangao1 @bknueven

@xiangao1 has implemented a self-schedule bidder class in the IDAES double loop PR: https://github.com/IDAES/idaes-pse/pull/638

**Outstanding Tasks:**
- [x] Review prototype from @xiangao1, provide feedback 
- [x] Add support for RTM prices (not just DAM)
- [x] Compare performance with and without realtime market (if applicable)
- [x] Create unit tests

**Comment by ksbeattie** [comment]
@adowling2, is this still needed for June?  @xiangao1 says that this functionality now exists in idaes-pse, is that correct?

**Comment by dguittet** [comment]
@adowling2 I think this is done now and has been released in idaes-pse.

RT bidding: https://github.com/IDAES/idaes-pse/blob/20ac4f6ac4d73ea6ba4414694986e8eda8d3f22f/idaes/apps/grid_integration/bidder.py#L342

Comparison was done as part of Xian's thesis, is that correct?

---

I added a test for the RT bidding here: https://github.com/IDAES/idaes-pse/blob/5b9bc4ef23e9b69e98770f743604dfbdef67847f/idaes/apps/grid_integration/tests/test_bidder.py#L256

**Comment by adowling2** [comment]
@dguittet Yes, @xiangao1 did the comparison in this Ph.D. thesis.

**Comment by adowling2** [comment]
@dguittet Which IDAES PR includes the RT bidding? Can you post a link here?

@ksbeattie This is ready to close once the PR @dguittet will post a link to is merged.

**Comment by dguittet** [comment]
https://github.com/IDAES/idaes-pse/pull/855
