### ISSUE TITLE
Integrate TEAL with Pyomo cost expressions into DISPATCHES workflow

### ISSUE THREAD

**Issue by adowling2** [gmlc-dispatches/dispatches#86]
Goal by June 30, 2022: Extend TEAL to generate Pyomo expressions for costing formulas. Integrate said formulas into the DISPATCHES workflow, starting with the NE case study.

Lead: 

Support: @klfrick2 @radhakrishnatg 

**Outstanding Tasks**:

**Comment by PaulTalbot-INL** [comment]
FYI The changes in TEAL have been merged with idaholab/TEAL#43; we're working on an initial demo for it in the dispatches nuclear case.

**Comment by PaulTalbot-INL** [comment]
It's worth noting that while we can demo TEAL integration, in order for DISPATCHES users to benefit from this we need RAVEN and TEAL as install dependencies; see #76 and idaholab/raven#1748.

**Comment by radhakrishnatg** [comment]
TEAL integration is demonstrated in this notebook https://github.com/GabrielSoto-INL/dispatches/blob/tealnb/dispatches/case_studies/nuclear_case/multiperiod_design_pricetaker_wTEAL.ipynb
The deterministic case is working, but the stochastic case needs some tweaking. After everything is fixed, the script containing helper functions will be pushed to `dispatches.util` folder. The content of the Jupyter notebook will be added to the nuclear case study's price-taker notebook.

**Comment by lbianchi-lbl** [comment]
Closing this after "promoting" the remaining outstanding task to its own issue #192 for June.
